import { For, Show, createResource, createSignal, onCleanup } from "solid-js"
import { useNavigate } from "@solidjs/router"
type View="dashboard"|"api"|"agent"|"projects"|"whiteboard"|"engineering"|"terminal"|"files"|"uml"|"docs"|"skills"|"settings"
const menu:Array<{id:View;label:string;icon:string}>=[
{id:"dashboard",label:"Dashboard",icon:"⌂"},{id:"agent",label:"AI Agent",icon:"✦"},{id:"projects",label:"Projects",icon:"▣"},{id:"whiteboard",label:"Whiteboard",icon:"◇"},{id:"engineering",label:"Engineering",icon:"⌘"},{id:"terminal",label:"Terminal",icon:">_"},{id:"files",label:"Files",icon:"▤"},{id:"uml",label:"UML / Architecture",icon:"⌬"},{id:"docs",label:"Documentation",icon:"▧"},{id:"skills",label:"Skills & Tools",icon:"⚙"},{id:"settings",label:"Settings",icon:"☷"},{id:"api",label:"GUI API",icon:"⌁"}]
const panels:Record<View,{title:string;subtitle:string;actions:string[]}>={
dashboard:{title:"Engineering Command Center",subtitle:"Build, test, document and ship software with Lumos Aris.",actions:["New project","Open repository","Create whiteboard","Start agent"]},
agent:{title:"AI Engineering Agent",subtitle:"Technical Lead, Backend, Frontend and QA agents with shared context.",actions:["New agent task","Run swarm","Review architecture","Generate tests"]},
projects:{title:"Projects",subtitle:"Requirements, tasks, roadmap, sprints and documents.",actions:["New project","Import repository","Create sprint","Open roadmap"]},
whiteboard:{title:"Whiteboard Studio",subtitle:"Infinite canvas for ideas, architecture, UML and implementation planning.",actions:["New board","Architecture diagram","Mind map","Generate from prompt"]},
engineering:{title:"Universal Engineering",subtitle:"Languages, frameworks, libraries, build systems and test runners.",actions:["Language registry","Tool registry","Dependency audit","Configure adapters"]},
terminal:{title:"Integrated Terminal",subtitle:"Controlled local shell access for builds, tests, Git and automation.",actions:["New terminal","PowerShell","Command Prompt","WSL"]},
files:{title:"Project Files",subtitle:"Repository browser with code intelligence and agent context.",actions:["Open folder","Search code","Find symbol","Compare files"]},
uml:{title:"UML & Architecture",subtitle:"Model systems with UML, C4, Mermaid, PlantUML and graphs.",actions:["Class diagram","Sequence diagram","C4 model","Generate architecture"]},
docs:{title:"Documentation Studio",subtitle:"README, API, ADR, changelog and architecture documentation.",actions:["New document","API reference","Architecture doc","Generate docs"]},
skills:{title:"Skills & Tools",subtitle:"Agent skills, tool adapters, MCP integrations and approvals.",actions:["Browse skills","Add tool","MCP servers","Permissions"]},
settings:{title:"Lumos Aris Settings",subtitle:"Desktop, agents, models, security, integrations and appearance.",actions:["Agent settings","Model providers","Security","Appearance"]},api:{title:"GUI API Console",subtitle:"Connect the Lumos Aris interface to its protected localhost engineering API.",actions:["API health","System status","Command console","PowerShell"]}}
async function getSystemInfo(){const api=(window as Window & {lumosWindows?:{systemInfo:()=>Promise<any>}}).lumosWindows;return api?api.systemInfo():null}
export default function ControlCenter(){
const navigate=useNavigate();const [view,setView]=createSignal<View>("dashboard");const [system]=createResource(getSystemInfo)
const native=()=>((window as Window & {lumosWindows?:any}).lumosWindows)
const [apiStatus,setApiStatus]=createSignal<{healthy:boolean;endpoint:string}>({healthy:false,endpoint:"http://127.0.0.1:47991"})
const [apiError,setApiError]=createSignal("")
const [apiBusy,setApiBusy]=createSignal(false)
const [projects,setProjects]=createSignal<any[]>([]);const [jobs,setJobs]=createSignal<any[]>([]);const [audit,setAudit]=createSignal<any[]>([])
const loadOperationalData=async()=>{const x=native();if(!x?.apiRequest)return;try{const [p,j,a]=await Promise.all([x.apiRequest("/v1/projects"),x.apiRequest("/v1/jobs"),x.apiRequest("/v1/audit")]);setProjects((p as any).projects||[]);setJobs((j as any).jobs||[]);setAudit((a as any).events||[])}catch(error){setApiError(error instanceof Error?error.message:String(error))}}
const refreshApi=async()=>{const x=native();if(!x)return;const s=await x.apiStatus();setApiStatus(s);const h=await x.apiHealth();setApiError(h.ok?"":(h.error||"API unavailable"))}
const apiAction=async(action:"startApi"|"stopApi")=>{const x=native();if(!x)return;setApiBusy(true);setApiError("");try{const result=await x[action]();if(!result.ok)setApiError(result.error||"API operation failed");await refreshApi()}catch(error){setApiError(error instanceof Error?error.message:String(error))}finally{setApiBusy(false)}}
void refreshApi();void loadOperationalData();const timer=setInterval(()=>{void refreshApi();void loadOperationalData()},5000);onCleanup(()=>clearInterval(timer))
const panel=()=>panels[view()]
const select=(id:View)=>{setView(id);if(id==="engineering")navigate("/engineering");if(id==="whiteboard")navigate("/whiteboard");if(id==="api")navigate("/api-console")}
return <div class="h-dvh w-full bg-background-base text-text-base flex overflow-hidden">
<aside class="w-60 shrink-0 border-r border-border-weak-base bg-surface-base flex flex-col"><div class="h-14 px-4 flex items-center gap-3 border-b border-border-weak-base"><div class="size-8 rounded-lg bg-surface-raised-base-active flex items-center justify-center text-text-strong">✦</div><div><div class="text-14-medium text-text-strong">Lumos Aris</div><div class="text-10-regular text-text-weak">AI Engineering OS</div></div></div>
<nav class="flex-1 overflow-auto p-2"><div class="px-2 py-2 text-10-medium uppercase text-text-weak">Workspace</div><For each={menu}>{item=><button onClick={()=>select(item.id)} class="w-full flex items-center gap-3 px-3 py-2 rounded-md text-12-regular text-text-base hover:bg-surface-raised-base-hover" classList={{"bg-surface-raised-base-active text-text-strong":view()===item.id}}><span class="w-5 text-center">{item.icon}</span><span>{item.label}</span></button>}</For></nav>
<div class="p-3 border-t border-border-weak-base"><div class="text-10-medium text-text-weak uppercase">System</div><div class="mt-2 flex items-center gap-2 text-11-regular"><span class="size-2 rounded-full bg-icon-success-base"></span>{system.loading?"Detecting Windows...":system()?.isWindows?"Windows API Ready":"Desktop API Ready"}</div></div></aside>
<main class="flex-1 min-w-0 overflow-auto"><header class="h-14 border-b border-border-weak-base flex items-center px-6 sticky top-0 bg-background-base/95 backdrop-blur z-10"><div class="text-12-regular text-text-weak">Workspace / </div><div class="ml-1 text-12-medium text-text-strong">{panel().title}</div><div class="ml-auto flex gap-2"><button class="px-3 py-1.5 rounded-md border border-border-weak-base text-11-regular">Command Palette</button><button class="px-3 py-1.5 rounded-md bg-surface-raised-base-active text-11-medium">Run Agent</button></div></header>
<div class="max-w-7xl mx-auto p-6"><div class="mb-6"><h1 class="text-24-medium text-text-strong">{panel().title}</h1><p class="mt-1 text-13-regular text-text-weak">{panel().subtitle}</p></div>
<div class="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-6"><For each={panel().actions}>{action=><button class="text-left rounded-lg border border-border-weak-base bg-surface-base p-4 hover:border-border-info-base"><div class="text-13-medium text-text-strong">{action}</div><div class="mt-1 text-11-regular text-text-weak">Open {action.toLowerCase()}</div></button>}</For></div>
<section class="grid grid-cols-1 xl:grid-cols-3 gap-4"><article class="xl:col-span-2 rounded-lg border border-border-weak-base bg-surface-base p-5"><div class="flex items-center justify-between"><h2 class="text-14-medium text-text-strong">Agent Pipeline</h2><span class="text-10-regular text-icon-success-base">READY</span></div><div class="mt-5 grid grid-cols-5 gap-2">{["Spec","Architecture","Code","Test","Deploy"].map((x,i)=><div class="rounded-md border border-border-weak-base p-3 text-center"><div class="text-11-medium text-text-strong">{i+1}</div><div class="mt-1 text-10-regular text-text-weak">{x}</div></div>)}</div><div class="mt-5 text-11-regular text-text-weak">Requirement → UML → task → implementation → tests → review → documentation → deployment.</div></article>
<article class="rounded-lg border border-border-weak-base bg-surface-base p-5"><h2 class="text-14-medium text-text-strong">Windows System</h2><Show when={system()} fallback={<div class="mt-4 text-11-regular text-text-weak">Loading native system information…</div>}>{s=><div class="mt-4 space-y-2 text-11-regular"><div class="flex justify-between"><span class="text-text-weak">Platform</span><span>{s().platform}</span></div><div class="flex justify-between"><span class="text-text-weak">Version</span><span>{s().release}</span></div><div class="flex justify-between"><span class="text-text-weak">Architecture</span><span>{s().arch}</span></div><div class="flex justify-between"><span class="text-text-weak">CPU</span><span>{s().cpuCount} cores</span></div><div class="flex justify-between"><span class="text-text-weak">Memory</span><span>{Math.round(s().freeMemoryBytes/1024/1024/1024)} GB free</span></div></div>}</Show></article></section>
<section class="mt-4 rounded-lg border border-border-weak-base bg-surface-base p-5"><div class="flex items-center justify-between"><div><h2 class="text-14-medium text-text-strong">Lumos Aris API Service</h2><p class="mt-1 text-11-regular text-text-weak">{apiStatus().endpoint}</p></div><span classList={{"text-icon-success-base":apiStatus().healthy,"text-icon-critical-base":!apiStatus().healthy}} class="text-11-medium">{apiStatus().healthy?"ONLINE":"OFFLINE"}</span></div><Show when={apiError()}><div class="mt-3 rounded-md bg-surface-raised-base-active p-3 text-11-regular text-icon-critical-base">{apiError()}</div></Show><div class="mt-4 flex gap-2"><button disabled={apiBusy()||apiStatus().healthy} onClick={()=>apiAction("startApi")} class="px-3 py-1.5 rounded-md border border-border-weak-base text-11-medium disabled:opacity-50">Start API</button><button disabled={apiBusy()||!apiStatus().healthy} onClick={()=>apiAction("stopApi")} class="px-3 py-1.5 rounded-md border border-border-weak-base text-11-medium disabled:opacity-50">Stop API</button><button disabled={apiBusy()} onClick={refreshApi} class="px-3 py-1.5 rounded-md bg-surface-raised-base-active text-11-medium disabled:opacity-50">Refresh</button></div></section><section class="mt-4 grid grid-cols-2 lg:grid-cols-4 gap-3"><For each={[["Languages","50+"],["UML targets","18"],["Build systems","24"],["Test runners","15"]]>{x=><div class="rounded-lg border border-border-weak-base bg-surface-base p-4"><div class="text-11-regular text-text-weak">{x[0]}</div><div class="mt-1 text-20-medium text-text-strong">{x[1]}</div></div>}</For></section></div></main></div>}
